name: Publicar no PyPI

on:
  push:
    tags:
      - 'v*'  # Executa apenas quando fizer push de uma tag como v0.1.0, v1.2.3, etc.

jobs:
  build-and-publish:
    name: Build e Publicação no PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Altere para a versão que seu pacote suporta

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Construir o pacote
        run: python -m build

      - name: Publicar no PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
